/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FamilyGroupDTO {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'memberCount' : bigint,
}
export type MediaType = { 'video' : null } |
  { 'none' : null } |
  { 'image' : null };
export interface MemoryPost {
  'id' : string,
  'title' : string,
  'description' : string,
  'author' : Principal,
  'imageUrl' : string,
  'timestamp' : bigint,
  'familyGroupId' : string,
}
export interface Message {
  'id' : string,
  'displayName' : string,
  'text' : [] | [string],
  'sender' : Principal,
  'mediaUrl' : [] | [string],
  'groupId' : string,
  'timestamp' : bigint,
  'mediaType' : MediaType,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMemberToGroup' : ActorMethod<[string, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFamilyGroup' : ActorMethod<[string, string], FamilyGroupDTO>,
  'createMemoryPost' : ActorMethod<
    [string, string, string, string, string],
    MemoryPost
  >,
  'deleteMessage' : ActorMethod<[string], undefined>,
  'getAllFamilyGroups' : ActorMethod<[], Array<FamilyGroupDTO>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDisplayName' : ActorMethod<[Principal], string>,
  'getFamilyGroupDetails' : ActorMethod<[string], FamilyGroupDTO>,
  'getMemoriesByGroup' : ActorMethod<[string], Array<MemoryPost>>,
  'getMessages' : ActorMethod<[string, bigint, [] | [bigint]], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeMemberFromGroup' : ActorMethod<[string, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<
    [string, string, [] | [string], [] | [string], MediaType],
    Message
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];