/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FamilyGroupDTO = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'memberCount' : IDL.Nat,
});
export const MemoryPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'imageUrl' : IDL.Text,
  'timestamp' : IDL.Int,
  'familyGroupId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MediaType = IDL.Variant({
  'video' : IDL.Null,
  'none' : IDL.Null,
  'image' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'displayName' : IDL.Text,
  'text' : IDL.Opt(IDL.Text),
  'sender' : IDL.Principal,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'groupId' : IDL.Text,
  'timestamp' : IDL.Int,
  'mediaType' : MediaType,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMemberToGroup' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFamilyGroup' : IDL.Func([IDL.Text, IDL.Text], [FamilyGroupDTO], []),
  'createMemoryPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [MemoryPost],
      [],
    ),
  'deleteMessage' : IDL.Func([IDL.Text], [], []),
  'getAllFamilyGroups' : IDL.Func([], [IDL.Vec(FamilyGroupDTO)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDisplayName' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getFamilyGroupDetails' : IDL.Func([IDL.Text], [FamilyGroupDTO], ['query']),
  'getMemoriesByGroup' : IDL.Func([IDL.Text], [IDL.Vec(MemoryPost)], ['query']),
  'getMessages' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Int)],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeMemberFromGroup' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), MediaType],
      [Message],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FamilyGroupDTO = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'memberCount' : IDL.Nat,
  });
  const MemoryPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'imageUrl' : IDL.Text,
    'timestamp' : IDL.Int,
    'familyGroupId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MediaType = IDL.Variant({
    'video' : IDL.Null,
    'none' : IDL.Null,
    'image' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'displayName' : IDL.Text,
    'text' : IDL.Opt(IDL.Text),
    'sender' : IDL.Principal,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'groupId' : IDL.Text,
    'timestamp' : IDL.Int,
    'mediaType' : MediaType,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMemberToGroup' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFamilyGroup' : IDL.Func([IDL.Text, IDL.Text], [FamilyGroupDTO], []),
    'createMemoryPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [MemoryPost],
        [],
      ),
    'deleteMessage' : IDL.Func([IDL.Text], [], []),
    'getAllFamilyGroups' : IDL.Func([], [IDL.Vec(FamilyGroupDTO)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDisplayName' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getFamilyGroupDetails' : IDL.Func([IDL.Text], [FamilyGroupDTO], ['query']),
    'getMemoriesByGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MemoryPost)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Int)],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeMemberFromGroup' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), MediaType],
        [Message],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };